### ISSUE TITLE
[Feature]: Revert to Original TextBlocks

### ISSUE THREAD

**Issue by seintun** [Crimson-Vision/Libriscan#208]
### Feature Description

Keep immutable attributes of Textblocks to revert to the original text blocks when the user wants to undo all changes made prior.

Some sort of original_ for text value, confidence score, print type, control of original textract would be great so that I can grab and replace.

The existing history stack would require much more work to check all the changes made and trace back.

Might need some backend additions to models, then UI click integration

### Use Case

As a user, I want to undo all changes and restore to the original text blocks with unmodified values.

**Comment by seintun** [comment]
@michaelsallee There appears to be a bug with One change will keep the button "Revert" greyed. Also I gonna fix up that style of the Revert yellow badge

I believe this "Revert to Original" is working as intended of resetting back to the first initial word's confidence score, print type/control, value, etc. Thus, losing all changes made.

Not meant for reverting one step back to the previous change, which the user could always check the audit log or change the dropdown manually.

Let me know if the purpose of this button has changed or if I am not on same page.

CC: @mhampson31 

<img width="608" height="887" alt="Image" src="https://github.com/user-attachments/assets/13c3706f-eda5-45d3-8523-cc3dfe7e3048" />

**Comment by seintun** [comment]
@michaelsallee fixed in PR https://github.com/Crimson-Vision/Libriscan/pull/257
 
- Audit timeline: display initial word and first change — Show the original word state and highlight the first change in the timeline.
- Revert to "Original extracted word" instead of the first change.
- - "Revert to Original" can not step back through the previous change. The user can/should change **inside** the word details, especially they can view the audit log.
- Fix revert button logic — Revert button now enables/disables correctly, including when there's only one change.
- Refactor and responsive improvements — Split audit history into separate modules (`audit_history.js` and `audit_history_renderer.js`). 
- Replaced custom CSS with Tailwind utilities for responsiveness across breakpoints.

<img width="437" height="532" alt="image" src="https://github.com/user-attachments/assets/cdcd54f2-88d4-429f-a1c2-646dc3010fd4" />

Mobile with better responsiveness. Icons instead of full texts on tab to minimize overlap
<img width="687" height="1032" alt="image" src="https://github.com/user-attachments/assets/7ba3b7c0-60a9-4b20-b999-ef02515e8f22" />

https://github.com/user-attachments/assets/576c850f-a427-4bb1-857b-2ef56af6c7c1

**Comment by michaelsallee** [comment]
just tried it and I'm still seeing the same. Can revert the first change and if you make 2 changes, it reverts to first change only

**Comment by michaelsallee** [comment]
[Error] Failed to load resource: You do not have permission to access the requested resource.
[Error] TypeError: null is not an object (evaluating 'this.prevWordBtn.onclick = () => this.navigation.goToPrevWord()')
	initializeEventListeners (main.js:85)
	WordDetails (main.js:11)
	(anonymous function) (main.js:257)
[Log] ✅ Tutorial initialized (tutorial.js, line 319)
[Log] HTMX navigation detected, reinitializing viewer... (page10, line 438, x2)
[Log] HTMX content swap detected, reinitializing word handlers... (page10, line 424)
[Log] HTMX navigation detected, reinitializing viewer... (page10, line 438)
[Error] TypeError: null is not an object (evaluating 'this.wordElement.textContent = word')
	updateWord (editor.js:76)
	updateWordDetails (main.js:118)
	dispatchEvent
	dispatchWordSelectedEvent (word_selector.js:89)
	handleWordClick (word_selector.js:22)
	click
	(anonymous function) (navigation.js:41)
[Error] TypeError: null is not an object (evaluating 'this.wordElement.textContent = word')
	updateWord (editor.js:76)
	updateWordDetails (main.js:118)
	dispatchEvent
	dispatchWordSelectedEvent (word_selector.js:89)
	handleWordClick (word_selector.js:22)
[Error] TypeError: null is not an object (evaluating 'this.wordElement.textContent')
	_setEditMode (editor.js:97)
	enterEditMode (editor.js:42)
	_handleKeydown (keyboard.js:32)
[Error] Error updating word:
TypeError: undefined is not an object (evaluating 'this.toggles[level]')
isLevelVisible — confidence-toggle.js:144
updateClasses — block_manager.js:26
updateWordBlock — update_handler.js:60
applyWordUpdate — update_handler.js:30
(anonymous function) — update_handler.js:14
	(anonymous function) (update_handler.js:21)
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this.toggles[level]')
	(anonymous function) (editor.js:57)

**Comment by seintun** [comment]
Should be fixed in https://github.com/Crimson-Vision/Libriscan/pull/262
